#git@gitlab.com:SuperManito/cishanjia.git
name: cishanjia
on:
  schedule:
    - cron: '10 */23 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-SuperManito-cishanjia

jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Sync-GitLab-repos-cishanjia
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://gitlab.com/SuperManito/cishanjia.git"
          source_branch: "main"
          destination_branch: "cishanjia"
          github_token: ${{ secrets.PAT }}
          fetch-depth: 0
          path: "."
          exclude: "'README.md'"
