#git@github.com:smallfawn/QLScriptPublic.git
name: smallfawn
on:
  schedule:
    - cron: '20 */20 * * *' 
  workflow_dispatch:
  #watch:
   # types: started
  repository_dispatch:
    types: sync-smallfawn-QLScriptPublic 
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Configure Git credentials
        run: |
          git config --global credential.helper store
          git config --global credential.helper 'cache --timeout=3600'
          
      - name: Set Git user identity
        run: |
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          
      - name: Backup README.md
        run: |
          cp README.md README_BACKUP.md
          git add README_BACKUP.md
          git commit -m "Backup README.md"
          git push

      - name: sync smallfawn-QLScriptPublic  
        uses: repo-sync/github-sync@v2
        if: env.PAT && github.event_name == 'schedule'
        with:
          source_repo: "https://github.com/smallfawn/QLScriptPublic.git" 
          source_branch: "main" 
          destination_branch: "smallfawn"  # #
          github_token: ${{ secrets.PAT }} 
          fetch-depth: 0
          path: "."
          
      - name: Restore README.md
        run: |
          mv README_BACKUP.md README.md
          git add README.md
          git commit -m "Restore README.md"
          git push
