name: Sync_Repositories

on:
  push:
    #branches: 
      #- main
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
  watch:
    types: started
jobs:
  sync:
    env:
      PAT: ${{ secrets.PAT }} 

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
        working-directory: .

      - name: 'Install requirements'
        run: pip install -r ./requirements.txt

      - name: 'Working'
        timeout-minutes: 350
        #run: bash ./main.sh
        run: python sync_repositories.py
        
      - name: 'Clean up cache'
        run: |
          git rm -r --cached .
          git reset --hard
        working-directory: ${{ github.workspace }}
