name: sync_repositories
  
on:  
  schedule:  
    - cron: '0 16 * * *' # 每天的16点执行
  workflow_dispatch:
  watch:
    types: started
  
jobs:  
  sync:  
    env:  
      PAT: ${{ secrets.PAT }}  
      PYTHON: python3  
  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v2  
  
      - name: Set up Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: 3.7  
  
      - name: Install dependencies  
        run: pip install --upgrade pip  
        working-directory: .  
  
      - name: Install requirements  
        run: pip install -r ./requirements.txt  
  
      - name: Working  
        timeout-minutes: 350  
        run: |  
          $PYTHON sync_repositories.py
