name: wd210010 # yml工作流文件名称
on:
  schedule:
    - cron: '1 */6 * * *' # 自定义设置拉取时间
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-wd210010-just_for_happy # 原仓库标签
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync wd210010-just_for_happy # 原仓库命名标签
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/wd210010/just_for_happy.git" # 拉取作者github仓库的地址url
          source_branch: "main" # 拉取当前仓库的指定分支名 默认一般master或者main
          destination_branch: "wd210010" # 自己仓库对应的分支名称
          github_token: ${{ secrets.PAT }} # 获取对应的secrets的密钥变量
          exclude: "'backup','README.md'"  # 拉取复刻仓库时，屏蔽一些文件，关键词
